### ISSUE TITLE
copia?

### ISSUE THREAD

**Issue by JeffersonRPM** [darkx09092003/darkx09092003.github.io#1]

**Comment by darkx09092003** [comment]
Can I use this please?

**Comment by darkx09092003** [comment]
Hello Jeff
First of all I'm really sorry for what I did
And I used your code for my repository and I am really really sorry about
that but I really needed a good landing page though I made some changes but
base is your site so can u please forget this and remove your issue please
as my mentor saw this i can't do the program please Jeff

If you see this kindly reply asap 🙏
